# Table of contents

* [Hi! WIP](README.md)
* [AD](AD.md)
* [Cool tools](<Cool tools.md>)
* [Cool websites](<Cool websites.md>)
* [LinuxSetUp](LinuxSetUp.md)
* [Path hijack](<Path hijack.md>)
* [Stabilize Shell](<Stabilize Shell.md>)
* [Pentesting API's](<Pentesting API's>)
* [VIM](VIM.md)
<<<<<<< HEAD
* [Calculate lines of code](<Calculate lines of code.md>)
=======
* [\[Calculate lines of code\](Calculate%20lines%20of%20code.md liczby linii kodu.md>)](calculate-lines-of-code-calculate-20lines-20of-20code.md-liczby-linii-kodu.md-greater-than.md)
>>>>>>> e215c17b7a1510ccf0d9bfc96db4b96f0f6bff19
* [OwnScripts](ownscripts/README.md)
  * [directory\_enum.py](OwnScripts/directory\_enum.py.md)
  * [hash\_cracker.py](OwnScripts/hash\_cracker.py.md)
  * [keylogger.py](OwnScripts/keylogger.py.md)
  * [network\_scanner.py](OwnScripts/network\_scanner.py.md)
  * [port\_scanner.py](OwnScripts/port\_scanner.py.md)
  * [ssh\_client\_dictionaryattck.py](OwnScripts/ssh\_client\_dictionaryattck.py.md)
  * [subdomain\_enum.py](OwnScripts/subdomain\_enum.py.md)
* [Proxy](proxy/README.md)
  * [Tworzenie tunelu proxy przez ssh](<Proxy/Tworzenie tunelu proxy przez ssh.md>)
* [QOL](qol/README.md)
  * [vi](QOL/vi.md)
  * [tmux](QOL/tmux.md)
* [Services](services/README.md)
  * [metasploit](Services/MYSQL.md)
  * [Metasploit](Services/SMTP.md)
  * [NFS](Services/NFS.md)
  * [SMB](Services/SMB.md)
* [Serwery HTTP](serwery-http/README.md)
  * [Python](<Serwery HTTP/Python.md>)
* [Tools](tools/README.md)
  * [Burp](Tools/Burp.md)
  * [DNS enum](<Tools/DNS enum.md>)
  * [wpsca](Tools/WordPress.md)
  * [crackmapexec](Tools/crackmapexec.md)
  * [chisel](Tools/chisel.md)
  * [enum4linux](Tools/enum4linux.md)
  * [curl](Tools/curl.md)
  * [ffuf](Tools/ffuf.md)
  * [Tools](tools/tools/README.md)
    * [hydra](Tools/hydra.md)
  * [less](Tools/less.md)
  * [gobuster](Tools/gobuster.md)
  * [netcat](Tools/netcat.md)
  * [msfvenom](Tools/msfvenom.md)
  * [nikto](Tools/nikto.md)
  * [pspy](Tools/pspy.md)
  * [rustscan](Tools/rustscan.md)
  * [TODO](Tools/rubeus.md)
  * [screen](Tools/screen.md)
  * [script](Tools/script.md)
  * [searchsploit](Tools/searchsploit.md)
  * [sqlmap](Tools/sqlmap.md)
  * [Tools](tools/tools-1/README.md)
    * [socat](Tools/socat.md)
  * [ssh](Tools/ssh.md)
  * [sqsh](Tools/sqsh.md)
